### ISSUE TITLE
Ignore Semaphore Disposed Exception

### ISSUE THREAD

**Issue by ashneilson** [ricado-group/dotnet-rabbitmq#1]
Ignore a `System.ObjectDisposedException` which can be thrown by the official RabbitMQ Client library.

Relates to this Merged Pull Request: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1015

`System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The semaphore has been disposed.)`

`---> System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at RabbitMQ.Client.Impl.AsyncConsumerWorkService.WorkPool.HandleConcurrent(Work work, IModel model, SemaphoreSlim limiter)`

`--- End of inner exception stack trace ---`

**Comment by ashneilson** [comment]
Resolved in 5b3a6c6
